name: CI-GO-NEW-2

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  check_manual_run:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # Prevent automatic run on PR
    steps:
      - name: Check if manual run exists
        id: check_status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: statuses } = await github.rest.repos.listCommitStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            
            const hasSuccess = statuses.some(status => 
              status.context === 'CI-GO-NEW-2' && status.state === 'success'
            );
            
            if (!hasSuccess) {
              core.setFailed('Manual run of CI-GO-NEW-2 workflow is required. Please trigger the workflow manually and wait for it to succeed.');
            }

  build:
    runs-on: ubuntu-latest
    name: Terratest Checks
    needs: check_manual_run
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.inputs.pr_number }}/head

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Report check status manually
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: parseInt('${{ github.event.inputs.pr_number }}'),
            });

            const sha = pr.data.head.sha;

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: 'success',
              context: 'CI-GO-NEW-2',  # Changed to match workflow name
              description: 'Manual build completed successfully',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`
            });
