name: CI

on:
  pull_request:
    types: [edited, opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # This ensures it runs whether build fails or succeeds
    steps:
      - name: Final Notification
        run: |
          echo "✅ CI check complete."
          echo "ℹ️ To re-run the workflow, edit the PR or trigger it manually from the Actions tab."
