name: CI

on:
  pull_request:
    types: [edited, opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # Run this job regardless of success/failure
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Update PR description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          gh auth setup-git
          gh pr view "$PR_NUMBER" --repo "$REPO" --json body -q '.body' > pr_body.txt

          # Check if the message already exists
          if ! grep -q "To re-run the workflow" pr_body.txt; then
            echo -e "\n\n➡️ **Note:** To re-run the workflow, edit the PR description or run it manually." >> pr_body.txt
            gh pr edit "$PR_NUMBER" --repo "$REPO" --body "$(cat pr_body.txt)"
          else
            echo "Message already present in PR body. Skipping update."
          fi
