name: CI

on:
  pull_request:
    types: [edited, opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # This step will only run if the previous steps fail
      - name: Notify in PR on failure
        if: failure()
        run: |
          gh pr edit "$PR_URL" --body "$UPDATED_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          UPDATED_BODY: |
            ⚠️ CI workflow failed.

            Please update the PR description or manually trigger the pipeline using the 'Run workflow' button.

        # Install GitHub CLI
      - name: Install GitHub CLI
        if: failure()
        run: |
          sudo apt-get update
          sudo apt-get install gh -y
